version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=sers
      - JWT_SECRET=your-secret-key
      - TWILIO_ACCOUNT_SID=your_account_sid
      - TWILIO_AUTH_TOKEN=your_auth_token
      - TWILIO_PHONE_NUMBER=your_twilio_number
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sers
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 